language: java
jdk:
  - oraclejdk8
after_success:
  - mvn clean test jacoco:report coveralls:report
notifications:
  email:
    recipients:
      - ahmed.hormal@gmail.com
    on_success: always # default: change
    on_failure: always # default: always